[package]
name = "ferrox"
version = "0.1.0"
authors = ["Sergio de Carvalho <sergio.carvalho@workday.com>"]
edition = "2018"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"